server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 注册到nacos必须指定nacos所在的路径
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #是否与服务注册于发现组件结合，通过serviceId转发到具体的服务
          lower-case-service-id: true
      routes: # 开始路由配置
        - id: gateway-resource #路由配置的名称 和具体服务无关
          # lb：load Balance(负载均衡)
          # resource-server路由的服务器的名称
          uri: lb://resource-server
          predicates: # 路由的路径配置
            # 访问 localhost:9000/image/xxxxx -> 访问resource-server服务中的内容
            - Path=/image/**

        - id: gateway-sys
          uri: lb://sys-service
          predicates:
            - Path=/v1/**

        - id: gateway-faq
          uri: lb://faq-service
          predicates:
            - Path=/v2/**

        - id: gateway-auth
          uri: lb://auth-service
          predicates:
            - Path=/oauth/**

